### ISSUE TITLE
lateral2 is not matched

### ISSUE THREAD

**Issue by mabeibei0404** [York-SDCNLab/Ghost-DeblurGAN#1]
RuntimeError: The size of tensor a (135) must match the size of tensor b (136) at non-singleton dimension 2

**Comment by AmaldevHari** [comment]
Hi, thanks for using Ghost-DeblurGAN. Could you please elaborate the problem, and copy-paste the entire error message. In particular it will help us solve it faster if you can provide the steps taken.

**Comment by yorklyb** [comment]
> RuntimeError: The size of tensor a (135) must match the size of tensor b (136) at non-singleton dimension 2

Hi Beibei. Are you using a custom dataset? If not, please follow this video tutorial (https://www.youtube.com/watch?v=JSCA2x3NBHs&t=44s) and I believe there will be no error reported.

**Comment by manavsingh415** [comment]
I had this same error. I resolved it by resizing/cropping the input to the neural network to be a square image of a size which is a power of 2, like 512 by 512 or 256 by 256
