### ISSUE TITLE
test result

### ISSUE THREAD

**Issue by kk047ddd** [York-SDCNLab/Ghost-DeblurGAN#3]
Does anyone reproduce the test results in the paper?PSNR:28.79 SSIM: 0.919
My test results on the GoPro dataset are PSNR: 27.53 SSIM: 0.917

**Comment by yorklyb** [comment]
Hi. Can you test the mobilenetv2 version with the same setup on the same computer? You will likely obtain results worse than those in the table again. I think this is a problem with the random seeds. The random seeds can affect both training and testing.

**Comment by kk047ddd** [comment]
Thanks for your reply, I did get worse results in the mobilenetv2 experiment. Different computer environment and random seeds may lead to different results.
