### ISSUE TITLE
some problems about FLOPs

### ISSUE THREAD

**Issue by Lyn4444** [York-SDCNLab/Ghost-DeblurGAN#4]
How do you calculate FLOPs, I try to calculate the FLOPs of your model

**Comment by AmaldevHari** [comment]
Hi,
You can use the following to estimate the FLOPs of model:
https://github.com/1adrianb/pytorch-estimate-flops

**Comment by AmaldevHari** [comment]
> How do you calculate FLOPs, I try to calculate the FLOPs of your model

Hi,
I am going to close this issue. If the problem is not resolved you can re-open.
